spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:h2:mem:testDB
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081